import { createSlice, createAsyncThunk, createEntityAdapter } from "@reduxjs/toolkit";
import { fetchPostsApi, publishPostApi } from "../api/mockApi";

// ---------------------------------------------------------------------------
// NORMALIZATION
// createEntityAdapter stores posts as { ids: [...], entities: { id: post } }
// instead of a plain array. This gives O(1) lookups/updates by id and mirrors
// how relational data is structured — the core "normalized state" concept.
// ---------------------------------------------------------------------------
const postsAdapter = createEntityAdapter({
  sortComparer: (a, b) => b.createdAt.localeCompare(a.createdAt), // newest first
});

const initialState = postsAdapter.getInitialState({
  status: "idle", // 'idle' | 'loading' | 'succeeded' | 'failed'
  publishStatus: "idle",
  error: null,
});

// ---------------------------------------------------------------------------
// ASYNC THUNKS — represent asynchronous data flows (mocked here, but the
// pattern is identical to calling a real REST/GraphQL API)
// ---------------------------------------------------------------------------
export const fetchPosts = createAsyncThunk("posts/fetchPosts", async () => {
  const posts = await fetchPostsApi();
  return posts;
});

export const publishPost = createAsyncThunk(
  "posts/publishPost",
  async ({ author, content, platforms }, { rejectWithValue }) => {
    try {
      const post = await publishPostApi({ author, content, platforms });
      return post;
    } catch (err) {
      return rejectWithValue(err.message);
    }
  }
);

const postsSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
    // --- CRUD (synchronous, local) ---
    postUpdated(state, action) {
      const { id, content, platforms } = action.payload;
      const existing = state.entities[id];
      if (existing) {
        existing.content = content;
        existing.platforms = platforms;
      }
    },
    postDeleted: postsAdapter.removeOne,
    likeToggled(state, action) {
      const post = state.entities[action.payload];
      if (post) {
        post.liked = !post.liked;
        post.likes += post.liked ? 1 : -1;
      }
    },
  },
  extraReducers: (builder) => {
    builder
      // fetchPosts lifecycle
      .addCase(fetchPosts.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.status = "succeeded";
        postsAdapter.setAll(state, action.payload); // normalize incoming array
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message;
      })
      // publishPost lifecycle
      .addCase(publishPost.pending, (state) => {
        state.publishStatus = "loading";
      })
      .addCase(publishPost.fulfilled, (state, action) => {
        state.publishStatus = "succeeded";
        postsAdapter.addOne(state, action.payload);
      })
      .addCase(publishPost.rejected, (state, action) => {
        state.publishStatus = "failed";
        state.error = action.payload || action.error.message;
      });
  },
});

export const { postUpdated, postDeleted, likeToggled } = postsSlice.actions;

// ---------------------------------------------------------------------------
// SELECTORS — generated by the entity adapter (selectAll, selectById, etc.)
// ---------------------------------------------------------------------------
export const {
  selectAll: selectAllPosts,
  selectById: selectPostById,
  selectIds: selectPostIds,
} = postsAdapter.getSelectors((state) => state.posts);

export const selectPostsStatus = (state) => state.posts.status;
export const selectPublishStatus = (state) => state.posts.publishStatus;
export const selectPostsError = (state) => state.posts.error;

export default postsSlice.reducer;
